### ISSUE TITLE
Linter error

### ISSUE THREAD

**Issue by iNerdGirl** [AtomLinter/linter-csslint#174]
Happens whenever I open a new CSS file in Atom this is the console output

```
Linter] Error running CSSLint Error: env: node: No such file or directory
    at ChildProcess.<anonymous> (/Users/autumnraine/.atom/packages/linter-csslint/node_modules/sb-exec/lib/index.js:56:20)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

**Comment by Arcanemagus** [comment]
Have you installed [Node.js](https://nodejs.org/en/) on your computer?

**Comment by catscarlet** [comment]
That is too bad. The readme only tells that `apm install linter-csslint`, doesn't tell anyone that it needs node too.
What is the worse? The error message is write in different language depend on OS's setting.
Because I'm using Chinese as system language, I got
 `�����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���` 
in UTF8, and try to convent it to ANSI and it turns to be 
`锟斤拷锟斤拷锟节诧拷锟斤拷锟解部锟斤拷锟筋，也锟斤拷锟角匡拷锟斤拷锟叫的筹拷锟斤拷
锟斤拷锟斤拷锟斤拷锟斤拷锟侥硷拷锟斤拷`
All I need is just `No such file or directory`
Feeling too bad.

Just set `D:\Atom x64\resources\app\apm\bin`(Depends on where you install Atom) to the `system path` and restart Atom, and the problem solved.

Yes, just using the apm's node. It's OK. Atom has already offer us a node_v6.9.5 so why the hell would we install a extra node.

**Comment by Arcanemagus** [comment]
@catscarlet CSSLint as a whole is terrible, you should _definitely_ look into switching to [`stylelint`](https://stylelint.io/) for your CSS linting needs (think JSCS vs. ESlint).

The error message is actually a quite difficult problem to solve, you can follow that in https://github.com/steelbrain/exec/issues/95.

Marking this as closed due to a lack of response from @iNerdGirl.

**Comment by lanakushnir** [comment]
installing [Node.js](https://nodejs.org/en/) fixed it for me
