### ISSUE TITLE
Missing CSS Rule - grid-column-gap

### ISSUE THREAD

**Issue by nmjbhoffmann** [AtomLinter/linter-csslint#180]
grid-column-gap throws an error saying it's an unknown property

**Comment by Arcanemagus** [comment]
You'll need to file this on [`csslint`](https://github.com/CSSLint/csslint), this project is just a wrapper around that for Atom.

As a note, I would _highly_ recommend moving to [stylelint.io](https://stylelint.io/) as development on `csslint` is essentially dead, in addition to the fact that `stylelint` is built on a modern CSS ecosystem (PostCSS) instead of using a custom parser. If you do move to that, [linter-stylelint](https://atom.io/packages/linter-stylelint) is the way to integrate it into Atom 😉.
