### ISSUE TITLE
Linter is not working for CSS

### ISSUE THREAD

**Issue by Raj2032** [AtomLinter/linter-csslint#187]
Everytime I save I get an error while it fails to highlight some of the syntax errors. Please refer to the link to see the error image.

https://i.stack.imgur.com/5I1ti.png

**Comment by Shkaf** [comment]
((I have the same problem(((

**Comment by Raj2032** [comment]
Linter is kinda shit to be honest. this fucking happens in C/C++ as well :(

**Comment by Arcanemagus** [comment]
You need to install [Node.js](https://nodejs.org/) and [csslint](https://github.com/CSSLint/csslint/wiki/Command-line-interface#running-on-nodejs) on your system in order to use this provider.

> Linter is kinda shit to be honest.

CSSLint definitely fits this, they stopped working on it years ago. I highly recommend you move to [stylelint](https://stylelint.io/).

> this fucking happens in C/C++ as well :(

I'm not sure what provider you are using, but the error you posted is a system configuration issue on your part as you haven't installed the required software to run this. If you are seeing the same error for "C/C++ as well" then it's likely you haven't installed something that it needs. Most providers are wrappers around external software that you need installed first before they can be used.

I'm closing this issue as it isn't a bug in the provider, thanks for taking the time to file an issue!
