### ISSUE TITLE
Updating to “linter-csslint@1.0.2” failed.

### ISSUE THREAD

**Issue by sublines** [AtomLinter/linter-csslint#40]
Never had this problem before. Any ideas?

> Failed to install linter-csslint because Git was not found.

> The linter-csslint package has module dependencies that cannot be installed without Git.

> You need to install Git and add it to your path environment variable in order to install this package.

> You can install Git by downloading, installing, and launching GitHub for Windows: https://windows.github.com

> Run apm -v after installing Git to see what version has been detected.

I ran CCleaner before opening Atom, can that cause issues?

**Comment by steelbrain** [comment]
It's because of [this][1] line. Maybe we should publish our csslint fork to npm and link to that.

[1]:https://github.com/AtomLinter/linter-csslint/blob/master/package.json#L15

**Comment by sublines** [comment]
I'm sorry I don't know what to do with this information. How can I update the package now? Would reinstall fix the problem?

**Comment by steelbrain** [comment]
@sublines You could extract the zip archieve of this repo https://github.com/AtomLinter/csslint
in your `~/.atom/packages/linter-csslint`'s `node_modules` lint

**Comment by sublines** [comment]
This must be somehow different on Windows.. 
C:\Users\username\AppData\Local\atom\packages includes three files
* atom-1.0.5-delta.nupkg
* atom-1.0.5-full.nupkg
* RELEASES

**Comment by Arcanemagus** [comment]
On Windows the path would be `C:\Users\username\.atom\packages\linter-csslint`.

**Comment by sublines** [comment]
great, thanks!

**Comment by awakekat** [comment]
I am getting the same problem on mac: 
Installing “linter-csslint@1.0.5” failed.
Failed to install linter-csslint because Git was not found.
The linter-csslint package has module dependencies that cannot be installed without Git.
You need to install Git and add it to your path environment variable in order to install this package.
Run apm -v after installing Git to see what version has been detected.

Running apm -v:
apm  1.0.1
npm  2.5.1
node 0.10.35
python 2.7.10
git 2.2.1

$which git:
/usr/local/git/bin/git

export PATH="/usr/local/git/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin"

Hope this helps
