### ISSUE TITLE
Installing "linter-csslinst@1.0.6" failed

### ISSUE THREAD

**Issue by Banjerr** [AtomLinter/linter-csslint#50]
I keep getting this error. I've uninstalled csslint and tried re-installing from the command line, but the same error; even when ran with sudo.

I try to open the log file, in the location the error message suggests, but it is empty. The location it suggests is "/private/var/folders/yg/bw29nm3j135dcd1l_9nfxr200000gn/T/apm-install-dir-11591-72046-1neiodu/npm-debug.log"

Any ideas?

**Comment by Arcanemagus** [comment]
Are you possibly running into issue #40? Development of `csslint` itself seems to have stalled which has forced us to fork it and use that to be able to get it to work well in this environment. Unfortunately although modern `npm` supports this, older versions doesn't support the package definition.

**Comment by steelbrain** [comment]
@Arcanemagus how about you publish it on npm with a prefix like `atom-linter-fork-csslint`?

**Comment by Arcanemagus** [comment]
@steelbrain You are the one that created that fork... :stuck_out_tongue:

If I was doing it I would have made it a real fork instead of the export then import as a new repo. In any case we could do that to work around broken clients that can't pull it down. It might also be just as good of an idea to simply import that code into here until `csslint` finally starts getting some work, I'm not sure...

**Comment by steelbrain** [comment]
@Arcanemagus Just do whatever you want, you're the one in change here.
