### ISSUE TITLE
config.cson problems created

### ISSUE THREAD

**Issue by inspiredmac** [AtomLinter/linter-csslint#58]
Attempted to install package linter-csslint.

In atom/config.cson, the followin is now written on lines 21 to 23:

linter-csslint':
  #csslint path. run 'which csslint' to find the path
  'executablePath': null

Upon opening Atom, the following warning in a pink box with a red flame icon is present at the top of the window:

Failed to load config.cson
[stdin]:23:18: error: missing '
'executablePath': null
^

**Comment by inspiredmac** [comment]
Problem may have resolved. I did both the Terminal session sudo xcodebuild and the Agreement approval after opening up XCode. I quit Atom and attempted a new intall of linter-csslint. The package loaded, is now present in Packages, and no further warnings are popping up.

**Comment by Arcanemagus** [comment]
Unless you manually typed those into your `config.cson` those lines would not have been there, especially since as it currently stands we are using a custom csslint since the origin repo hasn't been updated in months and we needed more functionality to use it properly.

I'll submit a PR that removes mention of that from the README.md. Marking this issue as closed as it's not a problem with `linter-csslint`.
